name: Testing Action

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev, main]

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Check Eslint
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.17'
      - run: |
          chmod +x ./script/lint.sh
          ./script/lint.sh
  tsc:
    runs-on: ubuntu-latest
    name: Check Typescript
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.17'
      - run: |
          chmod +x ./script/tsc.sh
          ./script/tsc.sh
  unit-test:
    runs-on: ubuntu-latest
    name: Check Mocha
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.17'
      - name: Mongo DB 설치
        uses: supercharge/mongodb-github-action@1.7.0
        with:
          mongodb-version: '4.0'
          mongodb-port: 27017
      - run: |
          chmod +x ./script/mocha.sh
          ./script/mocha.sh
        env:
          TEST_MONGO_URI: ${{secrets.TEST_MONGO_URI}}
          MAX_CAPACITY: ${{secrets.TEST_MAX_CAPACITY}}
